name: Model Training Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py  # to be changed

      - name: Upload Model to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: model.pkl  # to be changed
          name: "Model Release"
          tag_name: "v${{ github.run_number }}"
          body: "Automated release of model version ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
